const dataOrder = {
  education: {
    labels: [
      "University/College",
      "Secondary",
      "Primary",
      "No formal education"
    ],
    structure: [
      { education: "No formal education" },
      { education: "Primary" },
      { education: "Secondary" },
      { education: "University/College" }
    ]
  },
  gender: {
    labels: ["Female", "Male"],
    structure: [{ gender: "Male" }, { gender: "Female" }]
  },
  crossing_freq: {
    labels: ["Monthly", "Weekly", "Daily", "Never"],
    structure: [
      { crossing_freq: "Never" },
      { crossing_freq: "Daily" },
      { crossing_freq: "Weekly" },
      { crossing_freq: "Monthly" }
    ]
  },
  age: {
    labels: ["60-70", "50-60", "40-50", "30-40", "20-30", "10-20"],
    structure: [
      { age: "10-20" },
      { age: "20-30" },
      { age: "30-40" },
      { age: "40-50" },
      { age: "50-60" },
      { age: "60-70" }
    ]
  },
  country_of_residence: {
    labels: ["RWA", "UGA", "KEN", "TZA"],
    structure: [
      { country_of_residence: "KEN" },
      { country_of_residence: "UGA" },
      { country_of_residence: "RWA" },
      { country_of_residence: "TZA" }
    ]
  },
  primary_income: {
    labels: ["No", "Yes"],
    structure: [{ primary_income: "Yes" }, { primary_income: "No" }]
  },
  language: {
    labels: ["Lukiga", "Kinyarwanda", "Luganda", "Swahili", "English"],
    structure: [
      { language: "English" },
      { language: "Swahili" },
      { language: "Luganda" },
      { language: "Kinyarwanda" },
      { language: "Lukiga" }
    ]
  },
  produce: {
    labels: ["No", "Yes"],
    structure: [{ produce: "Yes" }, { produce: "No" }]
  },
  // procedurecommodity: {
  //   labels: [
  //     "Arrow Roots (nduma)",
  //     "Avocado",
  //     "Avocados",
  //     "Bananas",
  //     "Bananas - Matoke",
  //     "Bananas Cooking",
  //     "Bananas Ripe",
  //     "Beans",
  //     "Brinjals/Eggplant",
  //     "Bulls & Cows",
  //     "Bulls/Cows",
  //     "Cabbage",
  //     "Capsicums/pepper",
  //     "Carrots",
  //     "Cashew Nuts",
  //     "Cauliflower",
  //     "Chicken (Broiler)",
  //     "Chicken (Local)",
  //     "Chickens (Local)",
  //     "Chillies",
  //     "Clothes  & Shoes (New)",
  //     "Clothes (New)",
  //     "Clothes (Used)",
  //     "Clothes and Shoes (New)",
  //     "Clothes and Shoes (Used)",
  //     "Clothing and Shoes (Used)",
  //     "Cosmetics",
  //     "Cowpeas",
  //     "Cucumber",
  //     "Dolichos (Njahi)",
  //     "Duck",
  //     "Eggs",
  //     "Flowers",
  //     "Fresh Cassava",
  //     "Fresh Nile Perch",
  //     "Fresh peas",
  //     "Geese",
  //     "Goat",
  //     "Goats",
  //     "Greengrams",
  //     "Groundnuts",
  //     "Guavas",
  //     "Guinea Fowl",
  //     "Hides & Skins",
  //     "Honey",
  //     "Honey (Natural)",
  //     "Irish Potatoes",
  //     "Kales",
  //     "Lemons",
  //     "Lime",
  //     "Maize",
  //     "Maize Cereal",
  //     "Maize Flour",
  //     "Mangoes",
  //     "Meat of bulls/cows/Goats/Sheep",
  //     "Milk",
  //     "Millet",
  //     "Millet Flour",
  //     "Mwezi Moja",
  //     "New Clothes",
  //     "New Clothing and Shoes",
  //     "Nile Perch",
  //     "Nile Perch Dried or Preserved ",
  //     "Omena",
  //     "Onions",
  //     "Oranges",
  //     "Passion fruits",
  //     "Pawpaws (papaya)",
  //     "Pineapples",
  //     "Plastics",
  //     "Rice - Husked",
  //     "Rice - Processed",
  //     "Sheep",
  //     "Shoes (New)",
  //     "Sorghum",
  //     "Sorghum Cereal",
  //     "Sorghum Flour",
  //     "Sorghum Grains",
  //     "Spinach",
  //     "Sweet Potatoes",
  //     "Tilapia",
  //     "Tilapia Dried or Preserved",
  //     "Tilapia Fresh",
  //     "Timber",
  //     "Tomatoes",
  //     "Watermelon",
  //     "Wheat Flour",
  //     "Wheat Grain"
  //   ],
  //   structure: [
  //     { procedurecommodity: "Arrow Roots (nduma)" },
  //     { procedurecommodity: "Avocado" },
  //     { procedurecommodity: "Avocados" },
  //     { procedurecommodity: "Bananas" },
  //     { procedurecommodity: "Bananas - Matoke" },
  //     { procedurecommodity: "Bananas Cooking" },
  //     { procedurecommodity: "Bananas Ripe" },
  //     { procedurecommodity: "Beans" },
  //     { procedurecommodity: "Brinjals/Eggplant" },
  //     { procedurecommodity: "Bulls & Cows" },
  //     { procedurecommodity: "Bulls/Cows" },
  //     { procedurecommodity: "Cabbage" },
  //     { procedurecommodity: "Capsicums/pepper" },
  //     { procedurecommodity: "Carrots" },
  //     { procedurecommodity: "Cashew Nuts" },
  //     { procedurecommodity: "Cauliflower" },
  //     { procedurecommodity: "Chicken (Broiler)" },
  //     { procedurecommodity: "Chicken (Local)" },
  //     { procedurecommodity: "Chickens (Local)" },
  //     { procedurecommodity: "Chillies" },
  //     { procedurecommodity: "Clothes  & Shoes (New)" },
  //     { procedurecommodity: "Clothes (New)" },
  //     { procedurecommodity: "Clothes (Used)" },
  //     { procedurecommodity: "Clothes and Shoes (New)" },
  //     { procedurecommodity: "Clothes and Shoes (Used)" },
  //     { procedurecommodity: "Clothing and Shoes (Used)" },
  //     { procedurecommodity: "Cosmetics" },
  //     { procedurecommodity: "Cowpeas" },
  //     { procedurecommodity: "Cucumber" },
  //     { procedurecommodity: "Dolichos (Njahi)" },
  //     { procedurecommodity: "Duck" },
  //     { procedurecommodity: "Eggs" },
  //     { procedurecommodity: "Flowers" },
  //     { procedurecommodity: "Fresh Cassava" },
  //     { procedurecommodity: "Fresh Nile Perch" },
  //     { procedurecommodity: "Fresh peas" },
  //     { procedurecommodity: "Geese" },
  //     { procedurecommodity: "Goat" },
  //     { procedurecommodity: "Goats" },
  //     { procedurecommodity: "Greengrams" },
  //     { procedurecommodity: "Groundnuts" },
  //     { procedurecommodity: "Guavas" },
  //     { procedurecommodity: "Guinea Fowl" },
  //     { procedurecommodity: "Hides & Skins" },
  //     { procedurecommodity: "Honey" },
  //     { procedurecommodity: "Honey (Natural)" },
  //     { procedurecommodity: "Irish Potatoes" },
  //     { procedurecommodity: "Kales" },
  //     { procedurecommodity: "Lemons" },
  //     { procedurecommodity: "Lime" },
  //     { procedurecommodity: "Maize" },
  //     { procedurecommodity: "Maize Cereal" },
  //     { procedurecommodity: "Maize Flour" },
  //     { procedurecommodity: "Mangoes" },
  //     { procedurecommodity: "Meat of bulls/cows/Goats/Sheep" },
  //     { procedurecommodity: "Milk" },
  //     { procedurecommodity: "Millet" },
  //     { procedurecommodity: "Millet Flour" },
  //     { procedurecommodity: "Mwezi Moja" },
  //     { procedurecommodity: "New Clothes" },
  //     { procedurecommodity: "New Clothing and Shoes" },
  //     { procedurecommodity: "Nile Perch" },
  //     { procedurecommodity: "Nile Perch Dried or Preserved " },
  //     { procedurecommodity: "Omena" },
  //     { procedurecommodity: "Onions" },
  //     { procedurecommodity: "Oranges" },
  //     { procedurecommodity: "Passion fruits" },
  //     { procedurecommodity: "Pawpaws (papaya)" },
  //     { procedurecommodity: "Pineapples" },
  //     { procedurecommodity: "Plastics" },
  //     { procedurecommodity: "Rice - Husked" },
  //     { procedurecommodity: "Rice - Processed" },
  //     { procedurecommodity: "Sheep" },
  //     { procedurecommodity: "Shoes (New)" },
  //     { procedurecommodity: "Sorghum" },
  //     { procedurecommodity: "Sorghum Cereal" },
  //     { procedurecommodity: "Sorghum Flour" },
  //     { procedurecommodity: "Sorghum Grains" },
  //     { procedurecommodity: "Spinach" },
  //     { procedurecommodity: "Sweet Potatoes" },
  //     { procedurecommodity: "Tilapia" },
  //     { procedurecommodity: "Tilapia Dried or Preserved" },
  //     { procedurecommodity: "Tilapia Fresh" },
  //     { procedurecommodity: "Timber" },
  //     { procedurecommodity: "Tomatoes" },
  //     { procedurecommodity: "Watermelon" },
  //     { procedurecommodity: "Wheat Flour" },
  //     { procedurecommodity: "Wheat Grain" }
  //   ]
  // },
  procedurecommoditycat: {
    label: [
      " Bees and Their Products",
      "Cereals",
      "Clothing & Shoes",
      "Cosmetics",
      "Fish Products",
      "Fruits",
      "Legumes",
      "Legumes ",
      "Livestock & Livestock Products",
      "Poultry",
      "Pulses",
      "Timber",
      "Tubers",
      "Vegetables"
    ],
    structure: [
      { procedurecommoditycat: " Bees and Their Products" },
      { procedurecommoditycat: "Cereals" },
      { procedurecommoditycat: "Clothing & Shoes" },
      { procedurecommoditycat: "Cosmetics" },
      { procedurecommoditycat: "Fish Products" },
      { procedurecommoditycat: "Fruits" },
      { procedurecommoditycat: "Legumes" },
      { procedurecommoditycat: "Legumes " },
      { procedurecommoditycat: "Livestock & Livestock Products" },
      { procedurecommoditycat: "Poultry" },
      { procedurecommoditycat: "Pulses" },
      { procedurecommoditycat: "Timber" },
      { procedurecommoditycat: "Tubers" },
      { procedurecommoditycat: "Vegetables" }
    ]
  }
};

export default dataOrder;
